export const TASK_PRESETS = {
  'Sales & Outbound': [
    'Cold outreach (email / LinkedIn)',
    'Prospect research & list building',
    'Apollo sequence build',
    'Follow-up & reply handling',
    'Sales call / demo',
    'Demo booking & coordination',
    'Proposal preparation',
    'Pipeline & CRM update',
    'Partnership discussion',
    'Prospect outreach',
    'Weekly sales meeting',
    'Target account research',
    'Target account outreach — personalised',
  ],
  'Customer Success & Onboarding': [
    'Client onboarding session',
    'Client check-in call',
    'Health score review',
    'Renewal / upsell conversation',
    'Support ticket resolution',
    'Onboarding documentation',
    'CS reporting & tracking',
    'Client relationship call',
    'Chasing outstanding items from client',
    'Loading budgets',
    'Ticket counts',
    'Setting up accounts',
    'New account setup',
    'Budget entry — review/reconciliation',
    'Client email/communication',
    'Emailing clients',
    'Drafts',
    'Setting up customer success procedures',
  ],
  'Marketing & Content': [
    'LinkedIn content creation',
    'Blog / article writing',
    'Email newsletter',
    'Social media scheduling',
    'Marketing strategy & planning',
    'Campaign build & setup',
    'Analytics & reporting',
    'SEO / website update',
    'Design asset creation',
    'Award submission / PR',
  ],
  'Operations & Admin': [
    'Sprint planning & review',
    'Team coordination & comms',
    '1:1 with team member',
    'Process documentation',
    'Internal tooling / HQ build',
    'Reporting & analytics',
    'Emails & admin',
    'Hiring / HR task',
    'Contractor / supplier management',
  ],
  'Product & Tech': [
    'Feature testing & validation',
    'Bug reproduction & documentation',
    'Release sign-off',
    'Regression testing',
    'Test case writing',
    'Bug tracking update',
    'Sprint QA review',
    'Product strategy session',
    'Technical troubleshooting',
    'Automation testing',
  ],
  'Finance': [
    'Invoice processing',
    'Expense review',
    'Financial reporting',
    'Budget review',
    'Investor reporting',
    'Board / advisor meeting',
    'Funding round task',
    'Accounting support (Chris)',
  ],
  'Strategy & Planning': [
    'Investor meeting / comms',
    'Board meeting',
    'OKR / goal setting',
    'Quarterly planning',
    'Competitive research',
    'Partnership strategy',
    'Fundraising preparation',
  ],
  'External Accounting': [
    'Bookkeeping',
    'Payments',
    'Credit Control',
    'VAT',
    'End of Year',
    'Client Meetings',
  ],
  'In The Loop': [
    'Internal Meetings',
  ],
  'Other': [
    'Training / learning',
    'Internal meeting',
    'Cross-team collaboration',
    'Ad hoc task',
  ],
};